# Generated by Django 4.1 on 2022-08-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelcode',
            field=models.CharField(default='adea00fdf88740de8be3bcf6d2ec30aa', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='password',
            field=models.CharField(default='27d58c7434204990ad153a0923311b7c', max_length=50),
        ),
    ]
