# Generated by Django 4.1 on 2022-08-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_cancelcode_alter_booking_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancelcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
