# Generated by Django 4.1 on 2022-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_verifiedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedemail',
            name='verificationcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
